#![doc = "Generated by PhiLia093"]
use std::collections::HashMap;
use std::rc::Rc;
#[allow(unused)]
pub struct Interner {
    data: HashMap<Rc<str>, usize>,
    fast: Vec<Rc<str>>,
}
#[allow(unused)]
impl Interner {
    pub fn new(capacity: usize) -> Self {
        Self {
            data: HashMap::with_capacity(capacity),
            fast: Vec::with_capacity(capacity),
        }
    }
    pub fn intern(&mut self, s: &str) -> usize {
        if let Some(&id) = self.data.get(s) {
            id
        } else {
            let key = Rc::<str>::from(s);
            let id = self.fast.len();
            self.fast.push(key.clone());
            self.data.insert(key, id);
            id
        }
    }
    pub fn resolve(&self, id: &usize) -> Option<&str> {
        let string = self.fast.get(*id)?;
        Some(&(**string))
    }
}
